name: ci
on:
  workflow_dispatch: 
  push:
    branches:
      - "main"

jobs:
  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Set theme version in GitHub .ENV
      run: echo "GITHUB_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
    - run: echo ${{ env.GITHUB_VERSION }} 
    
    
  build:
      runs-on: self-hosted
      needs: pull
      defaults:
        run:
          working-directory: ./theme-grid
      steps:
      - name: Install packages  
        run: npm i
      - name: Build JS files
        run: npm run build
      - name: Build JAR theme 
        run: npx keycloakify
      - name: Move retrocompat from target floder to dir 
        run: mv build_keycloak/target/retrocompat-*.jar retrocompat-keycloak-theme.jar
      - name: Move theme-grid-keycloak-theme.jar from target folder to dir 
        run: mv build_keycloak/target/*.jar theme-grid-keycloak-theme.jar  
      
  release:
      runs-on: self-hosted
      needs: build
      defaults:
        run:
          working-directory: ./theme-grid
      steps:
      - name: Get theme version
        run: npm pkg get version
        id: get-version
      - name: Set theme version in GitHub .ENV
        run: echo "GITHUB_VERSION=$(echo ${{ steps.get-version.outputs.stdout }} | sed 's/\"//g')" >> $GITHUB_ENV
      - run: echo ${{ env.GITHUB_VERSION }} 
      - uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ env.GITHUB_VERSION }}
          tag_name: v${{ env.GITHUB_VERSION }}
          target_commitish: ${{ github.head_ref || github.ref }}
          generate_release_notes: true
          draft: false
          files: |
              ./theme-grid/theme-grid-keycloak-theme.jar
              ./theme-grid/retrocompat-keycloak-theme.jar
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
